In [1]:
import numpy as np
import pandas as pd
from collections import deque, defaultdict
import scipy.io

In [2]:
def connectivityExtractor(name):
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'connectivity' field from the 'Data' structured array
    data_structure = matlab_data['Data']
    connectivity_raw = data_structure['connectivity'][0, 0]  # Access the data (adjust indexing if needed)
    # Reshape or ensure it's a proper 2D array (if required)
    connectivity_data = connectivity_raw.squeeze()
    # Create a DataFrame from the connectivity data
    connectivity_df = pd.DataFrame(connectivity_data, columns=['Parent', 'Daughter1', 'Daughter2', 'Daughter3'])
    connectivity_df.replace(0, np.nan, inplace=True) #ensure all nonexistent vessels have NaN
    connectivity_df.at[0,'Parent']=0 #make sure first vessel is 0 (purposefully removed in last step for ease)
    # Save the DataFrame to inspect it
    return connectivity_df

def nodesExtractor(name): #extracts nodes and their corresponding information
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'connectivity' field from the 'Data' structured array
    data_structure = matlab_data['nodesC2']
    # Reshape or ensure it's a proper 2D array (if required)
    nodes_data = data_structure.squeeze()
    # Create a DataFrame from the connectivity data
    nodes_df = pd.DataFrame(nodes_data, columns=['NodeID', 'X', 'Y', 'Z', 'Degree'])
    # Save the DataFrame to inspect it
    return nodes_df

def edgesExtractor(name): #extracts segments to create a dataframe of from and to nodes
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'segments' field
    data_structure = matlab_data['segments']
    # Reshape or ensure it's a proper 2D array (if required)
    edges_data = data_structure.squeeze()
    # Create a DataFrame from the connectivity data
    edge_df = pd.DataFrame(edges_data, columns=['Old', 'From', 'To'])
    # Save the DataFrame to inspect it
    return edge_df

def mapIDExtractor(name):
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'mapID' field from the 'Data' structured array
    data_structure = matlab_data['Data']
    map_raw = data_structure['mapIDs'][0, 0]  # Access the data (adjust indexing if needed)
    # Reshape or ensure it's a proper 2D array (if required)
    map_data = map_raw.squeeze()
    # Create a DataFrame from the connectivity data
    map_df = pd.DataFrame(map_data, columns=['New', 'Old'])
    # Save the DataFrame to inspect it
    return map_df

def connectivityExtractor(name):
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'connectivity' field from the 'Data' structured array
    data_structure = matlab_data['Data']
    connectivity_raw = data_structure['connectivity'][0, 0]  # Access the data (adjust indexing if needed)
    # Reshape or ensure it's a proper 2D array (if required)
    connectivity_data = connectivity_raw.squeeze()
    # Create a DataFrame from the connectivity data
    connectivity_df = pd.DataFrame(connectivity_data, columns=['Parent', 'Daughter1', 'Daughter2', 'Daughter3'])
    connectivity_df.replace(0, np.nan, inplace=True) #ensure all nonexistent vessels have NaN
    connectivity_df.at[0,'Parent']=0 #make sure first vessel is 0 (purposefully removed in last step for ease)
    # Save the DataFrame to inspect it
    return connectivity_df

def lengthExtractor(name):
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'lengths' field from the 'Data' structured array
    data_structure = matlab_data['Data']
    length_raw = data_structure['lengths'][0, 0]  # Access the data (adjust indexing if needed)
    # Reshape or ensure it's a proper 2D array (if required)
    length_data = length_raw.squeeze()
    # Create a DataFrame from the data
    length_df = pd.DataFrame(length_data, columns=['Length'])
    # Save the DataFrame to inspect it
    return length_df

def radiusExtractor(name):
    file_path = 'Networks/Network_Vessels_' + name +'.mat'
    matlab_data = scipy.io.loadmat(file_path)
    # Extract the 'radius' field from the 'Data' structured array
    data_structure = matlab_data['Data']
    radius_raw = data_structure['rin'][0, 0]  # Access the data (adjust indexing if needed)
    # Reshape or ensure it's a proper 2D array (if required)
    radius_data = radius_raw.squeeze()
    # Create a DataFrame from the data
    radius_df = pd.DataFrame(radius_data, columns=['Radius'])
    # Save the DataFrame to inspect it
    return radius_df

In [ ]:
name = 'm2p4_060407'
output_name = 'GeneratorInput/'+name+'_left_lobe'
fromnode = 694
tonode = 701
segments = edgesExtractor(name)
maps = mapIDExtractor(name)
nodes = nodesExtractor(name)
newOldIDs = pd.merge(maps, segments, on='Old', how='left')
newOldIDs

     New  Old  From   To
0      0  357   133  694
1      1    1     1    0
2      2    2     3    2
3      3    3     5    4
4      4    4     7    6
..   ...  ...   ...  ...
632  632  632   657  679
633  633  633   679   25
634  634  634   705  428
635  635  635   705  609
636  636  636   778  595

[637 rows x 4 columns]

In [63]:
connectivity = connectivityExtractor(name)
length = lengthExtractor(name)
radius = radiusExtractor(name)
data = pd.concat([connectivity.iloc[:, :1], length, radius, connectivity.iloc[:, 1:]], axis=1)
data

     Parent       Length      Radius  Daughter1  Daughter2  Daughter3
0       0.0  3323.085543  430.610038      330.0      334.0        NaN
1       1.0  2625.260377   70.597362        NaN        NaN        NaN
2       2.0   521.498309   65.300600        NaN        NaN        NaN
3       3.0   360.531170   77.508484        NaN        NaN        NaN
4       4.0   828.105826   58.137866        NaN        NaN        NaN
..      ...          ...         ...        ...        ...        ...
632   632.0  1192.333519  142.357847      283.0      288.0      633.0
633   633.0   187.450204  144.242248       13.0      282.0        NaN
634   634.0  1079.491803   95.383926      174.0      221.0        NaN
635   635.0  1053.008739  202.430835      250.0      553.0        NaN
636   636.0   507.129072  107.293527      244.0      567.0        NaN

[637 rows x 6 columns]

In [ ]:
vessels = np.empty((0,0))
dl = np.empty((0,0))
dr = np.empty((0,0))
length = np.empty((0,0))
r1 = np.empty((0,0))
r2 = np.empty((0,0))
r = np.empty((0,0))
newVesID = int(newOldIDs[((newOldIDs['From'] == fromnode)&(newOldIDs['To']==tonode))].iloc[0,0])
vessels = np.append(vessels, newVesID)
i = 0
while len(vessels)<1000:
    if not np.isnan(data[data['Parent']==vessels[i]].iloc[0,3]):
        if data[data['Parent']==vessels[i]].iloc[0,2]>=.4*data.iloc[0,2]:
            dv1 = data[data['Parent']==vessels[i]].iloc[0,3]
            if data[data['Parent']==dv1].iloc[0,2]>=.4*data.iloc[0,2]:
                vessels = np.append(vessels, data[data['Parent']==vessels[i]].iloc[0,3])
            dv2 = data[data['Parent']==vessels[i]].iloc[0,4]
            if data[data['Parent']==dv2].iloc[0,2]>=.4*data.iloc[0,2]:
                vessels = np.append(vessels, data[data['Parent']==vessels[i]].iloc[0,4])
    if i+1 == len(vessels):
        break
    i+=1

for j in np.arange(len(vessels)):
    length = np.append(length,data[data['Parent']==vessels[j]].iloc[0,1]/1000)
    r1 = np.append(r1,data[data['Parent']==vessels[j]].iloc[0,2]/1000)
    r2 = np.append(r2,data[data['Parent']==vessels[j]].iloc[0,2]/1000)
    r = np.append(r,data[data['Parent']==vessels[j]].iloc[0,2]/1000)
    if j>i-1:
        dl = np.append(dl,np.nan)
        dr = np.append(dr,np.nan)
        continue
    dl = np.append(dl, data[data['Parent']==vessels[j]].iloc[0,3])
    dr = np.append(dr, data[data['Parent']==vessels[j]].iloc[0,4])

In [65]:
vessel_data = pd.DataFrame({'vesid':vessels,'dl':dl,'dr':dr})
vessel_data

    vesid     dl     dr
0   489.0  388.0  487.0
1   388.0  608.0  609.0
2   487.0  291.0  486.0
3   608.0  524.0  590.0
4   609.0  205.0  393.0
5   291.0    NaN    NaN
6   486.0   73.0  123.0
7   524.0  293.0  624.0
8   590.0  180.0  591.0
9   205.0    NaN    NaN
10  393.0   54.0  236.0
11   73.0    NaN    NaN
12  123.0    NaN    NaN
13  293.0    NaN    NaN
14  624.0  375.0  319.0
15  180.0    NaN    NaN
16  591.0  206.0  331.0
17   54.0    NaN    NaN
18  236.0    NaN    NaN
19  375.0  249.0  399.0
20  319.0    NaN    NaN
21  206.0    NaN    NaN
22  331.0  332.0  592.0
23  249.0    NaN    NaN
24  399.0   63.0  256.0
25  332.0  445.0  485.0
26  592.0  185.0  493.0
27   63.0    NaN    NaN
28  256.0    NaN    NaN
29  445.0  446.0  596.0
30  485.0  191.0  217.0
31  185.0    NaN    NaN
32  493.0   44.0  548.0
33  446.0  129.0  344.0
34  596.0  251.0  312.0
35  191.0    NaN    NaN
36  217.0    NaN    NaN
37   44.0    NaN    NaN
38  548.0   50.0  492.0
39  129.0    NaN    NaN
40  344.0  223.0  345.0
41  251.0    NaN    NaN
42  312.0    NaN    NaN
43   50.0    NaN    NaN
44  492.0  243.0  262.0
45  223.0    NaN    NaN
46  345.0  372.0  628.0
47  243.0    NaN    NaN
48  262.0    NaN    NaN
49  372.0  232.0  253.0
50  628.0  214.0  629.0
51  232.0    NaN    NaN
52  253.0    NaN    NaN
53  214.0    NaN    NaN
54  629.0  237.0  394.0
55  237.0    NaN    NaN
56  394.0   65.0  248.0
57   65.0    NaN    NaN
58  248.0    NaN    NaN

In [66]:
x1 = np.empty((0,0))
y1 = np.empty((0,0))
z1 = np.empty((0,0))
x2 = np.empty((0,0))
y2 = np.empty((0,0))
z2 = np.empty((0,0))

for m in np.arange(len(vessels)):
    fromnode = newOldIDs[newOldIDs['New']==vessels[m]].iloc[0,2]
    tonode = newOldIDs[newOldIDs['New']==vessels[m]].iloc[0,3]
    x1 = np.append(x1,nodes[nodes['NodeID']==fromnode].iloc[0,1]/1000)
    y1 = np.append(y1,nodes[nodes['NodeID']==fromnode].iloc[0,2]/1000)
    z1 = np.append(z1,nodes[nodes['NodeID']==fromnode].iloc[0,3]/1000)
    x2 = np.append(x2,nodes[nodes['NodeID']==tonode].iloc[0,1]/1000)
    y2 = np.append(y2,nodes[nodes['NodeID']==tonode].iloc[0,2]/1000)
    z2 = np.append(z2,nodes[nodes['NodeID']==tonode].iloc[0,3]/1000)

In [67]:
# Step 1: Create mapping from vesid (parents) to new sequential IDs
id_map = {old_id: new_id for new_id, old_id in enumerate(vessel_data['vesid'].dropna().unique())}

# Step 2: Build daughter-to-parent map
daughter_to_parent = {}
for _, row in vessel_data.iterrows():
    for daughter in [row['dl'], row['dr']]:
        if pd.notna(daughter):
            daughter_to_parent[daughter] = row['vesid']

# Step 3: Build result DataFrame
rows = []

for _, row in vessel_data.iterrows():
    current_id = row['vesid']
    new_index = id_map[current_id]

    # Get parent of current_id
    original_parent = daughter_to_parent.get(current_id, None)
    new_parent = id_map.get(original_parent, -10)  # If parent is not in vesid, use -10

    # Get new daughter indices if daughters are themselves vesid entries, else -10
    dl_new = id_map[row['dl']] if pd.notna(row['dl']) and row['dl'] in id_map else -10
    dr_new = id_map[row['dr']] if pd.notna(row['dr']) and row['dr'] in id_map else -10

    rows.append({'p': new_parent, 'dl': dl_new, 'dr': dr_new})

# Step 4: Create DataFrame
renumbered_ves = pd.DataFrame(rows)

print(renumbered_ves)

     p  dl  dr
0  -10   1   2
1    0   3   4
2    0   5   6
3    1   7   8
4    1   9  10
5    2 -10 -10
6    2  11  12
7    3  13  14
8    3  15  16
9    4 -10 -10
10   4  17  18
11   6 -10 -10
12   6 -10 -10
13   7 -10 -10
14   7  19  20
15   8 -10 -10
16   8  21  22
17  10 -10 -10
18  10 -10 -10
19  14  23  24
20  14 -10 -10
21  16 -10 -10
22  16  25  26
23  19 -10 -10
24  19  27  28
25  22  29  30
26  22  31  32
27  24 -10 -10
28  24 -10 -10
29  25  33  34
30  25  35  36
31  26 -10 -10
32  26  37  38
33  29  39  40
34  29  41  42
35  30 -10 -10
36  30 -10 -10
37  32 -10 -10
38  32  43  44
39  33 -10 -10
40  33  45  46
41  34 -10 -10
42  34 -10 -10
43  38 -10 -10
44  38  47  48
45  40 -10 -10
46  40  49  50
47  44 -10 -10
48  44 -10 -10
49  46  51  52
50  46  53  54
51  49 -10 -10
52  49 -10 -10
53  50 -10 -10
54  50  55  56
55  54 -10 -10
56  54  57  58
57  56 -10 -10
58  56 -10 -10

In [68]:
p = renumbered_ves['p'].to_numpy()
dlC = renumbered_ves['dl'].to_numpy()
drC = renumbered_ves['dr'].to_numpy()
vessel_data = pd.DataFrame({'x1':x1,'y1':y1,'z1':z1,'x2':x2,'y2':y2,'z2':z2,'l':length,
                            'r1':r1,'r2':r2,'r':r,'p':p,'dl':dlC,'dr':drC,
                            'inside':np.ones(len(vessels), dtype=int),'nt':np.ones(len(vessels), dtype=int)})
vessel_data = vessel_data.round(5)
vessel_data

,x1,y1,z1,x2,y2,z2,l,r1,r2,r,p,dl,dr,inside,nt
0,15.68767,11.52840,8.90626,14.64785,10.85026,11.52840,3.63631,0.18267,0.18267,0.18267,-10,1,2,1,1
1,14.64785,10.85026,11.52840,14.78348,11.25715,12.11612,0.83246,0.19066,0.19066,0.19066,0,3,4,1,1
2,14.64785,10.85026,11.52840,14.64785,9.85565,12.88468,1.85432,0.13295,0.13295,0.13295,0,5,6,1,1
3,14.78348,11.25715,12.11612,14.55743,11.93529,13.38199,1.75970,0.20436,0.20436,0.20436,1,7,8,1,1
4,14.78348,11.25715,12.11612,15.37120,11.30235,13.60804,1.95476,0.12115,0.12115,0.12115,1,9,10,1,1
5,14.64785,9.85565,12.88468,14.19576,10.21733,13.74366,1.39917,0.08813,0.08813,0.08813,2,-10,-10,1,1
6,14.64785,9.85565,12.88468,15.28078,9.67482,14.06013,1.70448,0.10179,0.10179,0.10179,2,11,12,1,1
7,14.55743,11.93529,13.38199,14.60264,11.61882,13.96971,0.79937,0.14151,0.14151,0.14151,3,13,14,1,1
8,14.55743,11.93529,13.38199,14.69306,12.47780,13.65324,0.77288,0.17737,0.17737,0.17737,3,15,16,1,1
9,15.37120,11.30235,13.60804,15.68767,10.62421,14.33139,1.16651,0.07804,0.07804,0.07804,4,-10,-10,1,1
10,15.37120,11.30235,13.60804,15.73288,11.89008,14.24097,0.99569,0.10291,0.10291,0.10291,4,17,18,1,1
11,15.28078,9.67482,14.06013,15.46162,9.90086,14.24097,0.39363,0.06704,0.06704,0.06704,6,-10,-10,1,1
12,15.28078,9.67482,14.06013,14.69306,9.53919,15.14516,1.54577,0.07636,0.07636,0.07636,6,-10,-10,1,1
13,14.60264,11.61882,13.96971,14.82869,11.43798,14.24097,0.55234,0.09500,0.09500,0.09500,7,-10,-10,1,1
14,14.60264,11.61882,13.96971,14.42180,11.61882,14.24097,0.87480,0.09184,0.09184,0.09184,7,19,20,1,1
15,14.69306,12.47780,13.65324,14.51222,13.38199,12.65864,1.64490,0.07627,0.07627,0.07627,8,-10,-10,1,1
16,14.69306,12.47780,13.65324,14.82869,12.61343,13.78887,0.30095,0.17737,0.17737,0.17737,8,21,22,1,1
17,15.73288,11.89008,14.24097,15.82330,12.20654,14.24097,0.38701,0.06768,0.06768,0.06768,10,-10,-10,1,1
18,15.73288,11.89008,14.24097,16.32060,11.48319,14.96432,1.09612,0.06754,0.06754,0.06754,10,-10,-10,1,1
19,14.42180,11.61882,14.24097,14.28618,11.16673,15.41641,1.47636,0.10131,0.10131,0.10131,14,23,24,1,1
20,14.42180,11.61882,14.24097,13.83408,11.34756,14.24097,0.83021,0.07408,0.07408,0.07408,14,-10,-10,1,1
21,14.82869,12.61343,13.78887,15.64246,13.02031,13.78887,1.04624,0.08791,0.08791,0.08791,16,-10,-10,1,1
22,14.82869,12.61343,13.78887,14.69306,12.88468,14.06013,0.46192,0.16376,0.16376,0.16376,16,25,26,1,1
23,14.28618,11.16673,15.41641,14.37660,10.66942,15.64246,0.62839,0.06026,0.06026,0.06026,19,-10,-10,1,1
24,14.28618,11.16673,15.41641,13.83408,11.07631,16.00413,0.89865,0.09264,0.09264,0.09264,19,27,28,1,1
25,14.69306,12.88468,14.06013,15.14516,13.87929,14.33139,1.37173,0.15535,0.15535,0.15535,22,29,30,1,1
26,14.69306,12.88468,14.06013,14.51222,12.88468,14.19576,0.57632,0.12957,0.12957,0.12957,22,31,32,1,1
27,13.83408,11.07631,16.00413,13.51762,10.53379,16.32060,0.79161,0.05932,0.05932,0.05932,24,-10,-10,1,1
28,13.83408,11.07631,16.00413,13.56283,11.25715,15.86851,0.39363,0.06872,0.06872,0.06872,24,-10,-10,1,1
29,15.14516,13.87929,14.33139,15.14516,14.01492,14.46701,0.19181,0.15156,0.15156,0.15156,25,33,34,1,1
30,15.14516,13.87929,14.33139,15.28078,13.96971,14.10534,0.31096,0.12632,0.12632,0.12632,25,35,36,1,1
31,14.51222,12.88468,14.19576,14.10534,12.83948,14.06013,0.54798,0.07199,0.07199,0.07199,26,-10,-10,1,1
32,14.51222,12.88468,14.19576,14.42180,12.83948,14.82869,0.90076,0.09395,0.09395,0.09395,26,37,38,1,1
33,15.14516,14.01492,14.46701,15.50683,14.82869,14.60264,1.04850,0.14252,0.14252,0.14252,29,39,40,1,1
34,15.14516,14.01492,14.46701,14.51222,14.10534,15.32599,1.24482,0.08499,0.08499,0.08499,29,41,42,1,1
35,15.28078,13.96971,14.10534,14.55743,14.42180,13.11073,1.94505,0.05626,0.05626,0.05626,30,-10,-10,1,1
36,15.28078,13.96971,14.10534,15.73288,13.96971,14.15055,0.57446,0.06292,0.06292,0.06292,30,-10,-10,1,1
37,14.42180,12.83948,14.82869,14.24097,12.97510,14.82869,0.29885,0.05733,0.05733,0.05733,32,-10,-10,1,1
38,14.42180,12.83948,14.82869,14.28618,12.79427,15.23557,0.51489,0.09404,0.09404,0.09404,32,43,44,1,1
39,15.50683,14.82869,14.60264,15.23557,15.28078,14.15055,0.87993,0.07704,0.07704,0.07704,33,-10,-10,1,1
40,15.50683,14.82869,14.60264,15.59725,14.91911,14.64785,0.14224,0.13623,0.13623,0.13623,33,45,46,1,1
41,14.51222,14.10534,15.32599,14.24097,13.92450,15.68767,0.53151,0.05478,0.05478,0.05478,34,-10,-10,1,1
42,14.51222,14.10534,15.32599,14.46701,14.51222,15.68767,0.66810,0.06520,0.06520,0.06520,34,-10,-10,1,1
43,14.28618,12.79427,15.23557,13.92450,13.11073,15.64246,0.72122,0.05255,0.05255,0.05255,38,-10,-10,1,1
44,14.28618,12.79427,15.23557,14.10534,12.61343,15.46162,0.35843,0.08979,0.08979,0.08979,38,47,48,1,1
45,15.59725,14.91911,14.64785,16.41102,14.78348,14.28618,1.06852,0.05696,0.05696,0.05696,40,-10,-10,1,1
46,15.59725,14.91911,14.64785,15.68767,15.14516,14.69306,0.27787,0.13096,0.13096,0.13096,40,49,50,1,1
47,14.10534,12.61343,15.46162,13.92450,12.47780,15.28078,0.29885,0.05968,0.05968,0.05968,44,-10,-10,1,1
48,14.10534,12.61343,15.46162,13.65324,12.52301,16.18497,1.03864,0.05764,0.05764,0.05764,44,-10,-10,1,1
49,15.68767,15.14516,14.69306,15.46162,15.32599,14.82869,0.37716,0.10337,0.10337,0.10337,46,51,52,1,1
50,15.68767,15.14516,14.69306,16.32060,15.77809,14.55743,1.07333,0.10291,0.10291,0.10291,46,53,54,1,1
51,15.46162,15.32599,14.82869,15.19036,15.46162,14.82869,0.39798,0.06292,0.06292,0.06292,49,-10,-10,1,1
52,15.46162,15.32599,14.82869,15.19036,15.73288,15.73288,1.23820,0.07022,0.07022,0.07022,49,-10,-10,1,1
53,16.32060,15.77809,14.55743,16.04934,16.41102,14.10534,0.94161,0.05714,0.05714,0.05714,50,-10,-10,1,1
54,16.32060,15.77809,14.55743,16.32060,16.00413,14.78348,0.41235,0.11020,0.11020,0.11020,50,55,56,1,1
55,16.32060,16.00413,14.78348,16.00413,16.23018,14.96432,0.46757,0.07067,0.07067,0.07067,54,-10,-10,1,1
56,16.32060,16.00413,14.78348,16.45623,16.13976,14.78348,0.22055,0.10540,0.10540,0.10540,54,57,58,1,1
57,16.45623,16.13976,14.78348,18.44544,17.22479,14.78348,2.78267,0.07612,0.07612,0.07612,56,-10,-10,1,1
58,16.45623,16.13976,14.78348,16.09455,16.45623,15.59725,1.08159,0.05108,0.05108,0.05108,56,-10,-10,1,1

In [69]:
vessel_data.to_csv(output_name+'.csv',index=False)
vessel_data.to_csv(output_name+'.dat', sep='\t', header=False, index=False)